require 'rake'

SOURCE_FOLDER = "graphics"
SOURCE_FILES = Rake::FileList["#{SOURCE_FOLDER}/**/*.xcf"]

# Remove initial 'graphics/' path element, and change file extension to png
OUTPUT_FILES = SOURCE_FILES.pathmap("%{^#{SOURCE_FOLDER}/,}X.png")

task :default => :png

desc "Compile Gimp .xcf files from graphics folder into .png files within res folder"
task :png => OUTPUT_FILES

rule ".png" => ->(f){source_for_png(f)} do |t|
  # Convert the file to a temporary directory, to avoid polluting the
  # file system if something goes wrong
  #
  require 'tmpdir'
  tmp_dir = Dir.mktmpdir
  begin
    tmp_output = File.join(tmp_dir,"a.png")
    system("convert #{t.source} #{tmp_output}")
    if !File.exist?(tmp_output)
      fail("could not convert #{t.source}; perhaps has layers?")
    end
    FileUtils.cp(tmp_output,t.name)
  ensure
    FileUtils.remove_entry_secure tmp_dir
  end
end

# Given an output file, find its corresponding source file
def source_for_png(png_file)
  src = SOURCE_FILES.detect{|f| f.ext('') == File.join(SOURCE_FOLDER,png_file.ext(''))}
end

desc "deletes some of the .png icons, for test purposes, so :png task actually does something"
task :cleansome do
  Rake::FileList["res/raw/*icon.png"].each do |f|
    File.delete(f)
  end
end

