package com.js.geometryapp;

import com.js.geometry.AlgorithmStepper;

public interface Algorithm {

	/**
	 * Get name of the algorithm. This will be displayed in the 'Operation:'
	 * combobox
	 */
	public String getAlgorithmName();

	/**
	 * Add widgets for user to customize this algorithm's operation
	 */
	public void prepareOptions(AlgorithmOptions options);

	/**
	 * Execute the algorithm
	 * 
	 * @param stepper
	 * @param input
	 *            a structure containing geometric objects generated by the
	 *            editor
	 */
	public void run(AlgorithmStepper stepper, AlgorithmInput input);
}
