package com.js.editor;

import com.js.geometry.Point;

public interface UserEventSource {

  /**
   * Transform view-space point to world point
   * 
   * @param viewPt
   *          point in view space
   * @return point in world
   */
  public Point viewToWorld(Point viewPt);

  /**
   * Get the manager that will handle events generated by this source
   */
  public UserEventManager getManager();

}
